# Run examples code to make sure it provides consistent results.

name: Examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dotnet:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./dotnet/
    - name: Build
      run: dotnet run --project ./dotnet/CbData.Examples.GameProviders.csproj --no-restore
